version: "3.7"

services:
  # clash
  clash:
    image: dreamacro/clash
    #container_name: clash
    volumes:
      - ./config.yaml:/root/.config/clash/config.yaml
    ports:
       - "${CLASH_CONTROL_PORT}:9090" # 控制api端口
       - "${CLASH_PORT}:7890"
    restart: always

  # 比较好看的图形界面
  yacd:
    image: haishanh/yacd
    #container_name: yacd
    ports:
      - "1234:80"
    restart: always
