version: "3.8"
services:
    nginx:
        image: nginx
        volumes:
            - ./conf.d:/etc/nginx/conf.d
            - ./certificate:/etc/nginx/certificate
        ports:
            - "443:443"
            - "80:80"
        networks:
            - qinglong_default
            - clash_default
networks:
    qinglong_default:
        external: true
    clash_default:
        external: true
