version: "3"

services:
  core-keeper:
    image: arguser/core-keeper-dedicated
    volumes:
      - ./server-files:/home/steam/core-keeper-dedicated
      - ./server-data:/home/steam/core-keeper-data
    env_file:
      - .env
    #restart: always
    stop_grace_period: 2m
